name: MoneySystemShop
main: metowa1227\msshop\Main
version: 5.0
api: 3.9.6
author: metowa1227
description: MoneySystem で使用可能なショッププラグイン
website: https://github.com/FuckingCodeGenerator/MoneySystem
depend: MoneySystem