name: MoneySystemLand
main: metowa1227\msland\Main
version: 0.2.5
api: 3.11.3
author: metowa1227
description: MoneySystemで使用可能な土地保護プラグイン
website: https://github.com/FuckingCodeGenerator/MoneySystem
