##土地のデフォルトの金額 (The price of the world for which the custom price is not set)
default-price: 150

##土地を識別する際に、Y座標も含める
enable-3d-judge: false
##高さ1ブロックごとの値段
price-per-height-block: 50

##LandParticleコマンドの有効化
enable-landparticle-command: true

##ワールド別の土地の金額 (Writing (world name: price))
custom-price: []

##土地保護ができないワールド
impossible-protection: []

##個人が所有できる最大土地数 (-1 unlimited)
limit: 5

##所有していない土地でも編集できるようにするワールド
freely-editable-world: []

##土地にテレポートできる機能 (true = enable | false = disable)
teleport: true
##OPのみ可能
teleport-only-op-allowed: false

##この値は変更しないでください
id: 1
